### ISSUE TITLE
PHP 7.2 Issue

### ISSUE THREAD

**Issue by sprankhub** [Strategery-Inc/Magento-InfiniteScroll#194]
Thanks for that nice extension! There is an issue with PHP 7.2, because you cache a non-numeric value in `Strategery_Infinitescroll_Model_Admin_Feed::setLastUpdate`. This crashes in `Mage_AdminNotification_Model_Feed::checkUpdate`:

    Notice: A non well formed numeric value encountered  in /var/www/shop/app/code/core/Mage/AdminNotification/Model/Feed.php on line 77

    #0 /var/www/shop/app/code/core/Mage/AdminNotification/Model/Feed.php(77): mageCoreErrorHandler(8, 'A non well form...', '/var/www/shop...', 77, Array)
    #1 /var/www/shop/app/code/community/Strategery/Infinitescroll/Model/Observer.php(29): Mage_AdminNotification_Model_Feed->checkUpdate()
    #2 /var/www/shop/app/code/core/Mage/Core/Model/App.php(1358): Strategery_Infinitescroll_Model_Observer->controllerActionPredispatch(Object(Varien_Event_Observer))
    #3 /var/www/shop/app/code/core/Mage/Core/Model/App.php(1337): Mage_Core_Model_App->_callObserverMethod(Object(Strategery_Infinitescroll_Model_Observer), 'controllerActio...', Object(Varien_Event_Observer))
    #4 /var/www/shop/app/Mage.php(451): Mage_Core_Model_App->dispatchEvent('controller_acti...', Array)
    #5 /var/www/shop/app/code/core/Mage/Core/Controller/Varien/Action.php(527): Mage::dispatchEvent('controller_acti...', Array)
    #6 /var/www/shop/app/code/core/Mage/Adminhtml/Controller/Action.php(167): Mage_Core_Controller_Varien_Action->preDispatch()
    #7 /var/www/shop/app/code/core/Mage/Core/Controller/Varien/Action.php(407): Mage_Adminhtml_Controller_Action->preDispatch()
    #8 /var/www/shop/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('index')
    #9 /var/www/shop/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
    #10 /var/www/shop/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
    #11 /var/www/shop/app/Mage.php(686): Mage_Core_Model_App->run(Array)
    #12 /var/www/shop/index.php(123): Mage::run('', 'store')
    #13 {main}

**Comment by gsomoza** [comment]
Great, thanks for reporting this. Unfortunately we're super busy preparing our clients for the end of the year and we won't be able to get to this just yet. Would you consider submitting a PR to help us release a fix for this?

**Comment by sprankhub** [comment]
Sure thing. Coming!

**Comment by sprankhub** [comment]
Here you go!

**Comment by project-magento** [comment]
- [ ] #**- > [`****`](url)**
